version: '3.8'

services:
  mongodb:
    image: mongo:6
    volumes:
      - mongodb_data_multi:/data/db
    environment:
      - MONGO_INITDB_DATABASE=aws-monitor
    ports:
      - "27017:27017"
    networks:
      - monitoring-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  backend:
    image: cmkh/pulsestack-multi-account:backend-latest
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/aws-monitor
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-here}
      - NODE_ENV=production
      - PORT=3001
      # Multi-Account AWS Credentials
      - BAMKOM_AWS_ACCESS_KEY_ID=${BAMKOM_AWS_ACCESS_KEY_ID}
      - BAMKOM_AWS_SECRET_ACCESS_KEY=${BAMKOM_AWS_SECRET_ACCESS_KEY}
      - BAMKOM_AWS_REGION=${BAMKOM_AWS_REGION:-us-east-1}
      - UNIFIED_AWS_ACCESS_KEY_ID=${UNIFIED_AWS_ACCESS_KEY_ID}
      - UNIFIED_AWS_SECRET_ACCESS_KEY=${UNIFIED_AWS_SECRET_ACCESS_KEY}
      - UNIFIED_AWS_REGION=${UNIFIED_AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID_2=${AWS_ACCESS_KEY_ID_2}
      - AWS_SECRET_ACCESS_KEY_2=${AWS_SECRET_ACCESS_KEY_2}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@admin.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-Admin@123}
    ports:
      - "3001:3001"
    networks:
      - monitoring-network
    depends_on:
      - mongodb
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s

  frontend:
    image: cmkh/pulsestack-multi-account:frontend-latest
    ports:
      - "3000:3000"
    networks:
      - monitoring-network
    depends_on:
      - backend
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s

volumes:
  mongodb_data_multi:

networks:
  monitoring-network:
    driver: overlay
    attachable: true